DIRECTORY="<REPLACE WITH DIRECTORY PATH FOR IMAGES TO TEST>"
CAMERA_ID="<REPLACE WITH CAMERA/DEVICE ID>"
ASSEMBLY_LINE_ID="<REPLACE WITH ASSEMBLY LINE ID>"
API_ENDPOINT="<REPLACE WITH API ENDPOINT URL>"
AUTH_TOKEN="<REPLACE WITH AUTH TOKEN>"
TIME_BETWEEN_REQUESTS="<REPLACE WITH A NUMBER FOR SECONDS BETWEEN UPLOAD REQUESTS>"

# FOR EXAMPLE
# DIRECTORY="../resources/images/extra_images"
# CAMERA_ID="CAM123456"
# ASSEMBLY_LINE_ID="ASM123456"
# API_ENDPOINT="https://xyz123.us-east-1.amazonaws.com/Prod/getsignedurl"
# AUTH_TOKEN="allow"
# TIME_BETWEEN_REQUESTS="1"

python3 uploadImages.py $DIRECTORY $CAMERA_ID $ASSEMBLY_LINE_ID $API_ENDPOINT $AUTH_TOKEN $TIME_BETWEEN_REQUESTS